// <auto-generated />
namespace PizzaMore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterPizzas_ColumnItem_RenameTo_ColumnTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterPizzas_ColumnItem_RenameTo_ColumnTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201702070731133_AlterPizzas_ColumnItem_RenameTo_ColumnTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
